name: uno
description: An event sourced UNO game made in Flutter.
publish_to: none
version: 0.0.1

environment:
  sdk: ^3.10.4
  flutter: ^3.38.5

dependencies:
  flutter:
    sdk: flutter
  dart_mappable: ^4.6.1
  fast_immutable_collections: ^11.1.0
  meta: ^1.17.0
  replay: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.10.5
  dart_mappable_builder: ^4.6.3

flutter:
  uses-material-design: true
